spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/board
    driver-class-name: org.postgresql.Driver
    #username: sa
    #password:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    #driver-class-name: org.h2.Driver

    sql-script-encoding: utf-8

  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          Charset: utf-8
          useUnicode: true
        jdbc.lob.non_contextual_creation: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE


my-app:
  client-id: post-1234
  client-secret: 123456
  test-user-name: tester
  test-user-password: 1234qwer
  grant-type: password